version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: androidx.core:core-ktx
    versions:
    - 1.5.0-beta02
    - 1.5.0-beta03
    - 1.6.0-alpha01
    - 1.6.0-alpha02
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.1
  - dependency-name: com.google.firebase:firebase-messaging
    versions:
    - 21.1.0
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.checkerframework:checker-qual
    versions:
    - 3.11.0
    - 3.12.0
  - dependency-name: com.google.android.gms:play-services-location
    versions:
    - 18.0.0
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.3-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.3-native-mt
  - dependency-name: com.google.firebase:firebase-config
    versions:
    - 20.0.3
    - 20.0.4
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
    - 1.4.0-alpha01
  - dependency-name: com.google.firebase:firebase-appindexing
    versions:
    - 19.2.0
  - dependency-name: com.google.firebase:firebase-datatransport
    versions:
    - 17.0.11
  - dependency-name: com.google.gms:google-services
    versions:
    - 4.3.5
  - dependency-name: androidx.biometric:biometric
    versions:
    - 1.1.0
  - dependency-name: com.google.android.play:core
    versions:
    - 1.9.1
